name: ci

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        sdk-version: ["8.0.301"]
        os: [ubuntu-22.04,ubuntu-24.04,windows-2022,macos-14]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.sdk-version }}

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test --no-build
        env:
          AZURE_SQL_TEST13_DATABASE: ${{ secrets.AZURE_SQL_TEST13_DATABASE }}
          AZURE_SQL_TEST13_SERVER: ${{ secrets.AZURE_SQL_TEST13_SERVER }}
          AZURE_SQL_TEST13_USER: ${{ secrets.AZURE_SQL_TEST13_USER }}
          AZURE_SQL_TEST13_PASSWORD: ${{ secrets.AZURE_SQL_TEST13_PASSWORD }}

  test-container-jammy:
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0.301-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test --no-build
        env:
          AZURE_SQL_TEST13_DATABASE: ${{ secrets.AZURE_SQL_TEST13_DATABASE }}
          AZURE_SQL_TEST13_SERVER: ${{ secrets.AZURE_SQL_TEST13_SERVER }}
          AZURE_SQL_TEST13_USER: ${{ secrets.AZURE_SQL_TEST13_USER }}
          AZURE_SQL_TEST13_PASSWORD: ${{ secrets.AZURE_SQL_TEST13_PASSWORD }}

  test-container-noble:
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0.301-noble
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test --no-build
        env:
          AZURE_SQL_TEST13_DATABASE: ${{ secrets.AZURE_SQL_TEST13_DATABASE }}
          AZURE_SQL_TEST13_SERVER: ${{ secrets.AZURE_SQL_TEST13_SERVER }}
          AZURE_SQL_TEST13_USER: ${{ secrets.AZURE_SQL_TEST13_USER }}
          AZURE_SQL_TEST13_PASSWORD: ${{ secrets.AZURE_SQL_TEST13_PASSWORD }}

